services:
  credit_core_system_db_mysql:
    container_name: credit_core_system_db_mysql
    image: ghcr.io/joseesco24/credit_core_system_db_mysql:v1.1.3
    networks:
      - credit_core_system_network
    ports:
      - target: 3306
        published: 3308
        protocol: tcp
    volumes:
      - type: volume
        source: credit_core_system_db_mysql_disc
        target: /var/lib/mysql

networks:
  credit_core_system_network:
    name: credit_core_system_network
    external: false
    driver: bridge

volumes:
  credit_core_system_db_mysql_disc:
